/**
 * Generated by 小🐔小🐔咕咕嘚.
 */
require("whatwg-fetch");
import * as React from "react"
import "normalize.css"
import {History} from "history"
import * as ReactDOM from "react-dom"

declare module "history"{
    export interface History {
        location: any
    }
}

declare global{
    export namespace ENV{
        const API_URL:string;
        const MONGODB:string;
        const SERVICE_WORKER_ON:boolean
    }
}

function reload(){
    fetch("./env.json",{
        credentials:"include"
    }).then((ENV)=>{
        global['ENV']=ENV
        return Promise.all([
            import("./config/routes"),
            import("guguder"),
            import("./bootstrap"),
            import('./register-service-worker')
        ]).then(([{rootRoutes},{Guguder},{getStore, history}])=>{
            ReactDOM.render(
                <Guguder store={getStore() as any} history={history} routes={rootRoutes}/>,
                document.querySelector("#root")
            )
        })
    })
}

reload()

declare const module:any;

if(module.hot) {
    module.hot.accept(['./config/routes.tsx',"guguder"],reload)
}